# --- First database schema

# --- !Ups

INSERT INTO `country` VALUES
  (1,'AD','Andorra'),
  (2,'AE','United Arab Emirates'),
  (3,'AF','Afghanistan'),
  (4,'AG','Antigua and Barbuda'),
  (5,'AI','Anguilla'),
  (6,'AL','Albania'),
  (7,'AM','Armenia'),
  (8,'AN','Netherlands Antilles'),
  (9,'AO','Angola'),
  (10,'AP','Asia/Pacific Region'),
  (11,'AQ','Antarctica'),
  (12,'AR','Argentina'),
  (13,'AS','American Samoa'),
  (14,'AT','Austria'),
  (15,'AU','Australia'),
  (16,'AW','Aruba'),
  (17,'AX','Aland Islands'),
  (18,'AZ','Azerbaijan'),
  (19,'BA','Bosnia and Herzegovina'),
  (20,'BB','Barbados'),
  (21,'BD','Bangladesh'),
  (22,'BE','Belgium'),
  (23,'BF','Burkina Faso'),
  (24,'BG','Bulgaria'),
  (25,'BH','Bahrain'),
  (26,'BI','Burundi'),
  (27,'BJ','Benin'),
  (28,'BL','Saint Barthelemy'),
  (29,'BM','Bermuda'),
  (30,'BN','Brunei Darussalam'),
  (31,'BO','Bolivia'),
  (32,'BR','Brazil'),
  (33,'BS','Bahamas'),
  (34,'BT','Bhutan'),
  (35,'BV','Bouvet Island'),
  (36,'BW','Botswana'),
  (37,'BY','Belarus'),
  (38,'BZ','Belize'),
  (39,'CA','Canada'),
  (40,'CC','Cocos (Keeling) Islands'),
  (41,'CD','Congo, The Democratic Republic of the'),
  (42,'CF','Central African Republic'),
  (43,'CG','Congo'),
  (44,'CH','Switzerland'),
  (45,'CI','Cote D''Ivoire'),
  (46,'CK','Cook Islands'),
  (47,'CL','Chile'),
  (48,'CM','Cameroon'),
  (49,'CN','China'),
  (50,'CO','Colombia'),
  (51,'CR','Costa Rica'),
  (52,'CU','Cuba'),
  (53,'CV','Cape Verde'),
  (54,'CX','Christmas Island'),
  (55,'CY','Cyprus'),
  (56,'CZ','Czech Republic'),
  (57,'DE','Germany'),
  (58,'DJ','Djibouti'),
  (59,'DK','Denmark'),
  (60,'DM','Dominica'),
  (61,'DO','Dominican Republic'),
  (62,'DZ','Algeria'),
  (63,'EC','Ecuador'),
  (64,'EE','Estonia'),
  (65,'EG','Egypt'),
  (66,'EH','Western Sahara'),
  (67,'ER','Eritrea'),
  (68,'ES','Spain'),
  (69,'ET','Ethiopia'),
  (70,'EU','Europe'),
  (71,'FI','Finland'),
  (72,'FJ','Fiji'),
  (73,'FK','Falkland Islands (Malvinas)'),
  (74,'FM','Micronesia, Federated States of'),
  (75,'FO','Faroe Islands'),
  (76,'FR','France'),
  (77,'GA','Gabon'),
  (78,'GB','United Kingdom'),
  (79,'GD','Grenada'),
  (80,'GE','Georgia'),
  (81,'GF','French Guiana'),
  (82,'GG','Guernsey'),
  (83,'GH','Ghana'),
  (84,'GI','Gibraltar'),
  (85,'GL','Greenland'),
  (86,'GM','Gambia'),
  (87,'GN','Guinea'),
  (88,'GP','Guadeloupe'),
  (89,'GQ','Equatorial Guinea'),
  (90,'GR','Greece'),
  (91,'GS','South Georgia and the South Sandwich Islands'),
  (92,'GT','Guatemala'),
  (93,'GU','Guam'),
  (94,'GW','Guinea-Bissau'),
  (95,'GY','Guyana'),
  (96,'HK','Hong Kong'),
  (97,'HM','Heard Island and McDonald Islands'),
  (98,'HN','Honduras'),
  (99,'HR','Croatia'),
  (100,'HT','Haiti'),
  (101,'HU','Hungary'),
  (102,'ID','Indonesia'),
  (103,'IE','Ireland'),
  (104,'IL','Israel'),
  (105,'IM','Isle of Man'),
  (106,'IN','India'),
  (107,'IO','British Indian Ocean Territory'),
  (108,'IQ','Iraq'),
  (109,'IR','Iran, Islamic Republic of'),
  (110,'IS','Iceland'),
  (111,'IT','Italy'),
  (112,'JE','Jersey'),
  (113,'JM','Jamaica'),
  (114,'JO','Jordan'),
  (115,'JP','Japan'),
  (116,'KE','Kenya'),
  (117,'KG','Kyrgyzstan'),
  (118,'KH','Cambodia'),
  (119,'KI','Kiribati'),
  (120,'KM','Comoros'),
  (121,'KN','Saint Kitts and Nevis'),
  (122,'KP','Korea, Democratic People''s Republic of'),
  (123,'KR','Korea, Republic of'),
  (124,'KW','Kuwait'),
  (125,'KY','Cayman Islands'),
  (126,'KZ','Kazakhstan'),
  (127,'LA','Lao People''s Democratic Republic'),
  (128,'LB','Lebanon'),
  (129,'LC','Saint Lucia'),
  (130,'LI','Liechtenstein'),
  (131,'LK','Sri Lanka'),
  (132,'LR','Liberia'),
  (133,'LS','Lesotho'),
  (134,'LT','Lithuania'),
  (135,'LU','Luxembourg'),
  (136,'LV','Latvia'),
  (137,'LY','Libyan Arab Jamahiriya'),
  (138,'MA','Morocco'),
  (139,'MC','Monaco'),
  (140,'MD','Moldova, Republic of'),
  (141,'ME','Montenegro'),
  (142,'MF','Saint Martin'),
  (143,'MG','Madagascar'),
  (144,'MH','Marshall Islands'),
  (145,'MK','Macedonia'),
  (146,'ML','Mali'),
  (147,'MM','Myanmar'),
  (148,'MN','Mongolia'),
  (149,'MO','Macau'),
  (150,'MP','Northern Mariana Islands'),
  (151,'MQ','Martinique'),
  (152,'MR','Mauritania'),
  (153,'MS','Montserrat'),
  (154,'MT','Malta'),
  (155,'MU','Mauritius'),
  (156,'MV','Maldives'),
  (157,'MW','Malawi'),
  (158,'MX','Mexico'),
  (159,'MY','Malaysia'),
  (160,'MZ','Mozambique'),
  (161,'NA','Namibia'),
  (162,'NC','New Caledonia'),
  (163,'NE','Niger'),
  (164,'NF','Norfolk Island'),
  (165,'NG','Nigeria'),
  (166,'NI','Nicaragua'),
  (167,'NL','Netherlands'),
  (168,'NO','Norway'),
  (169,'NP','Nepal'),
  (170,'NR','Nauru'),
  (171,'NU','Niue'),
  (172,'NZ','New Zealand'),
  (173,'OM','Oman'),
  (174,'PA','Panama'),
  (175,'PE','Peru'),
  (176,'PF','French Polynesia'),
  (177,'PG','Papua New Guinea'),
  (178,'PH','Philippines'),
  (179,'PK','Pakistan'),
  (180,'PL','Poland'),
  (181,'PM','Saint Pierre and Miquelon'),
  (182,'PN','Pitcairn Islands'),
  (183,'PR','Puerto Rico'),
  (184,'PS','Palestinian Territory, Occupied'),
  (185,'PT','Portugal'),
  (186,'PW','Palau'),
  (187,'PY','Paraguay'),
  (188,'QA','Qatar'),
  (189,'RE','Reunion'),
  (190,'RO','Romania'),
  (191,'RS','Serbia'),
  (192,'RU','Russian Federation'),
  (193,'RW','Rwanda'),
  (194,'SA','Saudi Arabia'),
  (195,'SB','Solomon Islands'),
  (196,'SC','Seychelles'),
  (197,'SD','Sudan'),
  (198,'SE','Sweden'),
  (199,'SG','Singapore'),
  (200,'SH','Saint Helena'),
  (201,'SI','Slovenia'),
  (202,'SJ','Svalbard and Jan Mayen'),
  (203,'SK','Slovakia'),
  (204,'SL','Sierra Leone'),
  (205,'SM','San Marino'),
  (206,'SN','Senegal'),
  (207,'SO','Somalia'),
  (208,'SR','Suriname'),
  (209,'ST','Sao Tome and Principe'),
  (210,'SV','El Salvador'),
  (211,'SY','Syrian Arab Republic'),
  (212,'SZ','Swaziland'),
  (213,'TC','Turks and Caicos Islands'),
  (214,'TD','Chad'),
  (215,'TF','French Southern Territories'),
  (216,'TG','Togo'),
  (217,'TH','Thailand'),
  (218,'TJ','Tajikistan'),
  (219,'TK','Tokelau'),
  (220,'TL','Timor-Leste'),
  (221,'TM','Turkmenistan'),
  (222,'TN','Tunisia'),
  (223,'TO','Tonga'),
  (224,'TR','Turkey'),
  (225,'TT','Trinidad and Tobago'),
  (226,'TV','Tuvalu'),
  (227,'TW','Taiwan'),
  (228,'TZ','Tanzania, United Republic of'),
  (229,'UA','Ukraine'),
  (230,'UG','Uganda'),
  (231,'UM','United States Minor Outlying Islands'),
  (232,'US','United States'),
  (233,'UY','Uruguay'),
  (234,'UZ','Uzbekistan'),
  (235,'VA','Holy See (Vatican City State)'),
  (236,'VC','Saint Vincent and the Grenadines'),
  (237,'VE','Venezuela'),
  (238,'VG','Virgin Islands, British'),
  (239,'VI','Virgin Islands, U.S.'),
  (240,'VN','Vietnam'),
  (241,'VU','Vanuatu'),
  (242,'WF','Wallis and Futuna'),
  (243,'WS','Samoa'),
  (244,'YE','Yemen'),
  (245,'YT','Mayotte'),
  (246,'ZA','South Africa'),
  (247,'ZM','Zambia'),
  (248,'ZW','Zimbabwe')
;

# --- !Downs

truncate table country;
''